=encoding utf8

=head1 NAME

Serge::Sync::Plugin::TranslationService::phrase - L<Phrase|https://phrase.com> synchronization plugin for L<Serge|https://serge.io/> based on L<Phrase CLI|https://phrase.com/cli>

=head1 SYNOPSIS

    ts
    {
        plugin                      phrase

        data
        {
            config_file              ./files/config/phrase_config_file.yml
        }
    }

=head1 DESCRIPTION

Integration between Serge (Free, Open Source Solution for Continuous Localization) and Phrase (Translation and localization management system for web and mobile applications),
implemented using command-line tool for the Phrase API.

=head1 ATTRIBUTES

=over

=item I<config_file>

Phrase CLI path to the configuration file.

=item I<upload_translations>

Upload translations on push. Default YES.

=item I<wait_for_uploads>

Wait for files to be processed while pushing. Default YES.

=item I<verbose>

Verbose output. Default NO.

=back

=head1 INSTALLATION

 cpanm Serge::Sync::Plugin::TranslationService::phrase

=head1 AUTHOR

Dragos Varovici <dvarovici.work@gmail.com>

=head1 COPYRIGHT AND LICENSE

This software is copyright (c) 2018-2020 by Dragos Varovici.

This is free software; you can redistribute it and/or modify it under
the same terms as the Perl 5 programming language system itself.
