=encoding utf8

=head1 NAME

Serge::Sync::Plugin::TranslationService::phraseapp - L<Phraseapp|https://phraseapp.com> synchronization plugin for L<Serge|https://serge.io/>

=head1 SYNOPSIS

    ts
    {
        plugin                      phraseapp

        data
        {
            config_file              ./files/config/phraseapp_config_file.yml
        }
    }

=head1 DESCRIPTION

Integration between Serge (Free, Open Source Solution for Continuous Localization) and Phraseapp (Translation and localization management system for web and mobile applications).

=head1 INSTALLATION

 cpanm Serge::Sync::Plugin::TranslationService::phraseapp

=head1 AUTHOR

Dragos Varovici <dvarovici.work@gmail.com>

=head1 COPYRIGHT AND LICENSE

This software is copyright (c) 2018-2019 by Dragos Varovici.

This is free software; you can redistribute it and/or modify it under
the same terms as the Perl 5 programming language system itself.
