=encoding utf8

=head1 NAME

Serge::Sync::Plugin::TranslationService::transifex - L<Transifex|https://www.transifex.com> synchronization plugin for L<Serge|https://serge.io/> based on L<Transifex CLI|https://docs.transifex.com/client/introduction>

=head1 SYNOPSIS

    ts
    {
        plugin                      transifex

        data
        {
            root_directory          ./files
        }
    }

=head1 DESCRIPTION

Integration between Serge (Free, Open Source Solution for Continuous Localization) and Transifex (Localization Automation Platform that powers the process of launching digital products into multiple languages),
implemented using the command-line tool for the Transifex API.

=head1 ATTRIBUTES

=over

=item I<root_directory>

Transifex CLI root directory.

=item I<push_translations>

Push the translation files to the server. Default YES.

=back

=head1 INSTALLATION

 cpanm Serge::Sync::Plugin::TranslationService::transifex

=head1 AUTHOR

Dragos Varovici <dvarovici.work@gmail.com>

=head1 COPYRIGHT AND LICENSE

This software is copyright (c) 2018-2019 by Dragos Varovici.

This is free software; you can redistribute it and/or modify it under
the same terms as the Perl 5 programming language system itself.
