=encoding utf8

=head1 NAME

Serge::Sync::Plugin::TranslationService::zanata - L<Zanata|http://zanata.org/> synchronization plugin for L<Serge|https://serge.io/>

=head1 SYNOPSIS

    ts
    {
        plugin                      zanata

        data
        {
            project_config         ./files/config/project_config.xml
            user_config            ./files/config/zanata.ini
        }
    }

=head1 DESCRIPTION

Integration between Serge (Free, Open Source Solution for Continuous Localization) and Zanata (Open source web-based system for translators to translate documentation and software online using a web-browser).

=head1 INSTALLATION

 cpanm Serge::Sync::Plugin::TranslationService::zanata

=head1 AUTHOR

Dragos Varovici <dvarovici.work@gmail.com>

=head1 COPYRIGHT AND LICENSE

This software is copyright (c) 2018-2019 by Dragos Varovici.

This is free software; you can redistribute it and/or modify it under
the same terms as the Perl 5 programming language system itself.
