skip_tags: true

image:
  - Visual Studio 2019
platform: x64

environment:
  matrix:
  - PERL_VERSION: 5.32.1.1
  - PERL_VERSION: 5.30.3.1
  - PERL_VERSION: 5.28.2.1
  - PERL_VERSION: 5.26.3.1

cache:
  - C:\strawberry

install:
  - ps: ./build/install.ps1

build_script:
  - ps: ./build/build.ps1

test_script:
  - ps: ./build/test.ps1