language: perl
env:
  - IN_TRAVIS=1 AUTHOR_TESTING=1
perl:
  - "5.34"
  - "5.32"
  - "5.30"
  - "5.28"
  - "5.26"
  - "5.24"
  - "5.22"
sudo: false
cache:
  directories:
    - $HOME/.carton
before_install:
  - cpanm Carton
install:
  - carton install --path $HOME/.carton
script:
  - export PERL5LIB=$HOME/.carton/lib/perl5
  - export PERL_CARTON_PATH=$HOME/.carton
  - carton exec cover -delete
  - perl -MDevel::Cover=+ignore,^local/,^t/ t/compile.t
  - perl -MDevel::Cover=+ignore,^local/,^t/ t/plugins.t
  - perl build-bin/dzil-plugins.pl -c build
  - perl build-bin/dzil-plugins.pl -c test
after_success:
  - carton exec cover -report codecov

