=encoding utf8

=head1 NAME

Serge::Sync::Plugin::TranslationService::lingohub - L<LingoHub|https://www.lingohub.com> synchronization plugin for L<Serge|https://serge.io/> based on L<LingoHub CLI|https://github.com/lingohub/lingohub_ruby>

=head1 SYNOPSIS

    ts
    {
        plugin                      lingohub

        data
        {
            project                 LingoHubProject
            root_directory          ./files
            resource_directory      resources
            target_languages   de es fr-ca
        }
    }

=head1 DESCRIPTION

Integration between Serge (Free, Open Source Solution for Continuous Localization) and LingoHub (One platform for developers and translators that makes localizing software, mobile or web applications and on-demand),
implemented using the command-line tool for the LingoHub API.

=head1 ATTRIBUTES

=over

=item I<project>

LingoHub project.

=item I<root_directory>

Root directory.

=item I<resource_directory>

Resource directory.

=item I<source_language>

Source language.

=item I<target_languages>

List of target languages.

=back

=head1 INSTALLATION

 cpanm Serge::Sync::Plugin::TranslationService::lingohub

=head1 AUTHOR

Dragos Varovici <dvarovici.work@gmail.com>

=head1 COPYRIGHT AND LICENSE

This software is copyright (c) 2018-2020 by Dragos Varovici.

This is free software; you can redistribute it and/or modify it under
the same terms as the Perl 5 programming language system itself.
