=encoding utf8

=head1 NAME

Serge::Sync::Plugin::TranslationService::mojito - L<Mojito|http://www.mojito.global/> synchronization plugin for L<Serge|https://serge.io/> based on L<Mojito CLI|http://www.mojito.global/docs/guides/install/>

=head1 SYNOPSIS

    ts
    {
        plugin                      mojito

        data
        {
            repository_name         MojitoRepositoryName
            application_properties  ./files/config/mojito.properties
            source_files_path       ./files/source
            localized_files_path    ./files/target
        }
    }

=head1 DESCRIPTION

Integration between Serge (Free, Open Source Solution for Continuous Localization) and Mojito (Open source automation platform that enables continuous localization),
implemented using the command-line tool for the Mojito API.

=head1 ATTRIBUTES

=over

=item I<repository_name>

Mojito Repository name

=item I<application_properties>

Mojito CLI configuration file (server connection properties)

=item I<source_files_path>

Directory of the source resource files

=item I<source_locale>

Source locale

=item I<localized_files_path>

Directory of the localized resource files


=item I<import_translations>

Import translations flag. Default YES

=item I<inheritance_mode>

Inheritance mode. Default REMOVE_UNTRANSLATED

=item I<file_type>

File type

=item I<status_equal_target>

Status equal target

=item I<status_pull>

Status pull. Default ACCEPTED

=item I<destination_locales>

List of destination locales

=back

=head1 INSTALLATION

 cpanm Serge::Sync::Plugin::TranslationService::mojito

=head1 AUTHOR

Dragos Varovici <dvarovici.work@gmail.com>

=head1 COPYRIGHT AND LICENSE

This software is copyright (c) 2018-2020 by Dragos Varovici.

This is free software; you can redistribute it and/or modify it under
the same terms as the Perl 5 programming language system itself.
